### ISSUE TITLE
iPad shows both SimpleSelect dropdown and the default dropdown 

### ISSUE THREAD

**Issue by prashantsani** [pioul/jQuery.SimpleSelect#2]
Hello,

When the SimpleSelect is clicked on iPad (iOS 8) , it shows both the custom dropdown(made by SimpleSelect) and iPad Default white color dropdown.

**Comment by pioul** [comment]
Good catch.

I developed this plugin with desktop browsers in mind, so the fact that it doesn't work out of the box on mobile doesn't come as a surprise. The rationale behind this is that there's less room for fancy customization on mobile, and native elements often are to be preferred in terms of UX.

I expected developers to provide their own way of switching this plugin on and off depending on the environment. One could imagine, for a mobile+desktop responsive site, listening to `resize` events and only using this plugin on desktop-size resolutions.

What I didn't imagine, however, is that iOS would misbehave in such a way, making browser/platform sniffing unavoidable in that configuration – and I'm not really happy with that.

So, what I think SimpleSelect really lacks is a built-in switch between native and custom selects depending on the context. I'll have to think about this a little more and hopefully come up with something else than browser sniffing – otherwise I'll make sure it's solid and well-tested to prevent iOS from biting us again.

As I was saying in a comment on another issue you opened today, I probably won't have time to work on that in the near future, so even though I'm closing this issue for the time being (and will update it when a solution exists), feel free to continue the discussion here – help is always appreciated.

Until then!
