### ISSUE TITLE
Disable a <option> in dropdown not the whole dropdown

### ISSUE THREAD

**Issue by prashantsani** [pioul/jQuery.SimpleSelect#4]
Hello, 
There should be a way to disable the <option> and not the whole dropdown.

**Comment by pioul** [comment]
Hey there!

You're right, there should be such a thing; unfortunately, the plugin currently only supports disabling the whole select, not specific options or option groups.

Your version of `addOption` makes it possible to *display* SS options as disabled when their select counterpart is (although `if (selectOption.prop("disabled"))` is a better condition), but that only solves part of the problem since they'll keep *behaving* pretty much like they're not disabled.

To make them behave differently, the plugin will have to go through some other modifications. I'm adding this feature to my todo list, but will probably not have time to work on it in the near future; I'll comment on this thread when it's finally there.
If you come up with a patch before then, please send a PR, and I'll review it in no time.

Cheers!
